# Generated by Django 2.0.1 on 2018-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('result', models.CharField(blank=True, default='()', max_length=200)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
