# Generated by Django 2.0.1 on 2018-01-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0003_auto_20180123_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordings',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='recordings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to=settings.AUTH_USER_MODEL),
        ),
    ]
