# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0005_auto_20180123_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='device',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
