# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0006_recordings_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='unknown', max_length=7)),
                ('age', models.CharField(default='unknown', max_length=7)),
            ],
        ),
    ]
